# -*- coding: utf-8 -*-
"""assignment-10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ug_Yn9Q8yTcgn2CCcq3Mi8V8raS6hfD0
"""

user_name = "infotech_ibo"
input_name = input ("please give me your user name: ")
if input_name == user_name :
  print (" hello ibo! The password is: 12345")
else :
  print (" hello",input_name, "see you later.")

