# -*- coding: utf-8 -*-
"""assignment-10/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WwZNPkUip5lA2eBYptbylKBVPPcRvR_n
"""

age = input ("Are you a cigarette addict older than 75 years old? yes or no? ")
chronic = input ("Do you have a severe chronic disease? yes or no? ")
immune = input ( "Is your immune system too weak? yes or no? ")
if age == "yes" :
  age_new = True
else :
  age_new = False

if chronic == "yes" :
  chronic_new = True
else :
  chronic_new = False

if immune == "yes" :
  immune_new = True
else :
  immune_new = False

print ("You are in risky group: ", age_new or chronic_new or immune_new)

